data_reader:
  dataset: "squad_bert"
  train_file_path: "https://korquad.github.io/dataset/KorQuAD_v1.0_train.json"
  valid_file_path: "https://korquad.github.io/dataset/KorQuAD_v1.0_dev.json"
  squad_bert:
    lang_code: "ko"
    max_seq_length: 512
    context_stride: 64
    max_question_length: 64

iterator:
  batch_size: 12

token:
  names:
    - "feature"
  types:
    - "feature"
  tokenizer:
    subword:
      name: "wordpiece"
      wordpiece:
        vocab_path: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased-vocab.txt"
    word:
      name: "bert_basic"
      bert_basic:
        do_lower_case: true

  feature:
    vocab:
      pretrained_path: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased-vocab.txt"
      pretrained_token: "all"
    indexer":
      do_tokenize: false

model:
  name: "bert_for_qa"
  bert_for_qa:
    pretrained_model_name: "bert-base-multilingual-cased"
    answer_maxlen: 30

trainer:
  log_dir: "logs/test/bert_for_qa/"
  num_epochs: 5
  early_stopping_threshold: 10
  metric_key: "f1"
  verbose_step_count: 100
  eval_and_save_step_count: 1000

optimizer:
  learning_rate: 0.00003
  op_type: "adamw"
  adamw:
    weight_decay: 0.01
  lr_scheduler_type: "warmup_linear"
  warmup_linear:
    warmup_proportion: 0.1

seed_num: 42
